"""
Django settings for storeapp project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from ckeditor_demo.settings import CKEDITOR_UPLOAD_PATH
from django.conf.global_settings import AUTH_USER_MODEL, MEDIA_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jfu9ri1+qd3#yjunh-t3te!kpuo&^#42(r@8mh^!)d6vl31)45'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stores.apps.StoresConfig',
    'ckeditor',
    'corsheaders',  # Add this line
    'rest_framework.authtoken',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'cloudinary',
    'oauth2_provider'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',  # ✅ OAuth2 Support
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # ✅ Token Authentication
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}



CKEDITOR_UPLOAD_PATH = "ckeditor/images/"

import cloudinary

cloudinary.config(
    cloud_name="dj0oslp3a",
    api_key="393547919889753",
    api_secret="6_mEs6LTpPUCRXuglyGoMy4meg4",  # Click 'View API Keys' above to copy your API secret
    secure=True
)

MIDDLEWARE = [
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add this line
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

import pymysql

pymysql.install_as_MySQLdb()

ROOT_URLCONF = 'storeapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",  # React Native
    "http://127.0.0.1:8000",  # Django backend
    "http://172.29.32.1:8000"  # Windows Local IP
]

WSGI_APPLICATION = 'storeapp.wsgi.application'
CORS_ALLOW_ALL_ORIGINS = True  # Allow all domains (use only in development)
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/auth tokens in requests

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'store_db',  # Use the actual database name
        'USER': 'django_user',  # Use the MySQL user you created
        'PASSWORD': 'password',  # The password you set
        'HOST': 'localhost',  # Keep this as 'localhost'
        'PORT': '3306',  # Default MySQL port
    },
    'chat_db': {
        'ENGINE': 'djongo',
        'NAME': 'hand_tracker_db',  
        'CLIENT': {
            'host': 'mongodb://localhost:27017/',
        }
    }
}




MEDIA_ROOT = '%s/stores/static/' % BASE_DIR

AUTH_USER_MODEL = 'stores.NguoiDung'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLIENT_ID = 'rS2UcRRkboVcqHlnMVgCoBC8D6cxA7XEDvyrajfA'
CLIENT_SECRET = 'zwwgWbWmGyro8QSLj47EVOumbuQQ3WieGDaOZJekzTRheIEe7L4sEqwYJmw559L7SXgb2TOacHf3df89OStnSm7yDIDXqNygXzvTMfl1P4ppobVQb7hkuaR3G02sUAoa'

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",  # React Native Metro bundler
    "http://127.0.0.1:8000",  # Django backend
]
