# Generated by Django 5.1.4 on 2025-01-09 10:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('vai_tro', models.CharField(choices=[('user', 'Nguoi dung thuong'), ('seller', 'Nguoi ban'), ('admin', 'Quan tri vien'), ('staff', 'Nhan vien he thong')], default='user', max_length=20)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nu'), ('other', 'Khac')], max_length=10, null=True)),
                ('da_xac_minh', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chu_so_huu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cua_hang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanhGiaNguoiBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('binh_luan', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_nguoi_ban', to='stores.cuahang')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_nguoi_ban', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('cod', 'Thanh toan khi nhan hang'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('zalo', 'Zalo Pay'), ('momo', 'MoMo')], max_length=20)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong_ton', models.PositiveIntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='stores.cuahang')),
                ('danh_muc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_pham', to='stores.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGiaSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('binh_luan', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_san_pham', to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='stores.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='stores.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ThongKeDoanhThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.PositiveIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_don_hang', models.PositiveIntegerField()),
                ('nguoi_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu', to='stores.cuahang')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_nhan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
