# Generated by Django 5.1.4 on 2025-01-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_thongkedoanhthu_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongKeBanHangCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.PositiveIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('tong_don_hang', models.PositiveIntegerField()),
                ('tong_san_pham_ban', models.PositiveIntegerField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_ban_hang', to='stores.cuahang')),
            ],
            options={
                'unique_together': {('cua_hang', 'thang', 'nam')},
            },
        ),
        migrations.CreateModel(
            name='ThongKeDoanhThuSanPhamCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.PositiveIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_san_pham_ban', models.PositiveIntegerField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu_san_pham', to='stores.cuahang')),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu_san_pham', to='stores.sanpham')),
            ],
            options={
                'unique_together': {('cua_hang', 'san_pham', 'thang', 'nam')},
            },
        ),
        migrations.CreateModel(
            name='ThongKeTongSanPhamCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.PositiveIntegerField()),
                ('nam', models.PositiveIntegerField()),
                ('tong_san_pham', models.PositiveIntegerField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_tong_san_pham', to='stores.cuahang')),
            ],
            options={
                'unique_together': {('cua_hang', 'thang', 'nam')},
            },
        ),
    ]
