# Generated by Django 5.1.4 on 2025-01-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_thongkedoanhthusanphamcuahang_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThongKeTongSanPhamCuaHang',
        ),
    ]
