# Generated by Django 5.1.4 on 2025-01-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_delete_thongketongsanphamcuahang'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongKeDonHangVaSanPhamCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_dat_hang', models.DateTimeField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cuahang')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.sanpham')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='thongkebanhangcuahang',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thongkebanhangcuahang',
            name='cua_hang',
        ),
        migrations.AlterUniqueTogether(
            name='thongkedoanhthu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thongkedoanhthu',
            name='danh_muc',
        ),
        migrations.RemoveField(
            model_name='thongkedoanhthu',
            name='nguoi_ban',
        ),
        migrations.RemoveField(
            model_name='thongkedoanhthu',
            name='san_pham',
        ),
        migrations.DeleteModel(
            name='ThongKeDoanhThuSanPhamCuaHang',
        ),
        migrations.DeleteModel(
            name='ThongKeBanHangCuaHang',
        ),
        migrations.DeleteModel(
            name='ThongKeDoanhThu',
        ),
    ]
