# Generated by Django 5.1.4 on 2025-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_thongkedonhangvasanphamcuahang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
