# Generated by Django 5.1.4 on 2025-01-12 18:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_cuahang_active_sanpham_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='anh_dai_dien',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
