# Generated by Django 5.1.4 on 2025-01-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_remove_nguoidung_anh_dai_dien_nguoidung_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongKeDoanhThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=0)),
                ('gia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ngay_thanh_toan', models.DateTimeField()),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu', to='stores.cuahang')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu', to='stores.danhmuc')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_ke_doanh_thu', to='stores.sanpham')),
            ],
        ),
    ]
