# Generated by Django 5.1.4 on 2025-01-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_thongkedoanhthu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanphamdonhang',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.sanpham'),
        ),
    ]
