# Generated by Django 5.1.4 on 2025-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_sanphamdonhang_san_pham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m'),
        ),
    ]
