# Generated by Django 5.1.4 on 2025-02-05 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0014_alter_nguoidung_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="donhang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("pending", "Đang xử lý"),
                    ("shipped", "Đã gửi hàng"),
                    ("delivered", "Đã giao"),
                    ("canceled", "Đã hủy"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="donhang",
            name="phuong_thuc_thanh_toan",
            field=models.CharField(
                choices=[
                    ("cod", "Thanh toán khi nhận hàng"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("zalo", "Zalo Pay"),
                    ("momo", "MoMo"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="KhoHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong_nhap", models.PositiveIntegerField()),
                ("ngay_nhap", models.DateTimeField(auto_now_add=True)),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kho_hang",
                        to="stores.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoSanhSanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diem_tuong_dong",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "san_pham_goc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="so_sanh_goc",
                        to="stores.sanpham",
                    ),
                ),
                (
                    "san_pham_so_sanh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="so_sanh_tuong_tu",
                        to="stores.sanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThanhToan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phuong_thuc",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("zalo", "Zalo Pay"),
                            ("momo", "MoMo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ma_giao_dich", models.CharField(max_length=100, unique=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ngay_thanh_toan", models.DateTimeField(auto_now_add=True)),
                (
                    "don_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thanh_toan",
                        to="stores.donhang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YeuCauXacMinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yeu_cau_xac_minh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
