# Generated by Django 5.1.4 on 2025-02-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0015_donhang_trang_thai_nguoidung_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nguoidung",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="https://console.aiven.io/static/images/service-onboarding-banner.4d81fe52.png",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="nguoidung",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
